version: '2'
services:
    ping_container:
        build:
            dockerfile: ping/ping_image
        networks:
            - ping_pong_net
    pong_container:
        build:
            dockerfile: pong/pong_image
        networks:
            - ping_pong_net
        depends_on:
            - ping_container

networks:
    ping_pong_net: