version: '2'
services:
    ping_container:
        build:
            dockerfile: ping/ping_image
        ports:
            - "6000:6000"
    pong_container:
        build:
            dockerfile: pong/pong_image
        ports:
            - "7000:7000"